title: h e l l o
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3511328850872815
  brandStrength: 0.820143137127161
  rhythmicContrast: 0.7197771328501403
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
  lightness: 0.09547223034314811
typography_spectrum: 0.2361702
description: shall we begin
layout_spectrum: 0.6598334982991219
name: jonnieclout
